name: GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate GitHub Stats
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: saahilsanganeriya
          
      - name: Update README with stats
        run: |
          echo "📊 **GitHub Stats:**" >> temp_stats.md
          echo "" >> temp_stats.md
          echo "<div align=\"center\">" >> temp_stats.md
          echo "  <img src=\"https://github-readme-stats.vercel.app/api?username=saahilsanganeriya&show_icons=true&theme=vue-dark&hide_border=true&count_private=true\" alt=\"GitHub Stats\" width=\"48%\"/>" >> temp_stats.md
          echo "  <img src=\"https://github-readme-stats.vercel.app/api/top-langs/?username=saahilsanganeriya&layout=compact&theme=vue-dark&hide_border=true\" alt=\"Top Languages\" width=\"48%\"/>" >> temp_stats.md
          echo "</div>" >> temp_stats.md
          echo "" >> temp_stats.md
          
          # Insert stats before the final separator
          sed '/^---$/i\
          $(cat temp_stats.md)' README.md > temp_readme.md
          mv temp_readme.md README.md
          rm temp_stats.md
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "📊 Update GitHub stats"
          git push
