name: Profile Update

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Update last activity timestamp
        run: |
          # Simple way to keep profile active
          date=$(date '+%Y-%m-%d')
          echo "<!-- Profile updated: $date -->" >> README.md
          
      - name: Commit if changed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "🤖 Daily profile update"
          git push
